// Catálogo SPECS — edite/adicione produtos aqui.
// Como é venda somente no atacado, não exibimos preço fixo: o valor e a
// quantidade mínima são combinados pelo WhatsApp.
// `images` é opcional — quando presente, vira a galeria do quickview (várias fotos do mesmo produto).
const PRODUCTS = [
  {
    id: "conjunto-laise-azul",
    name: "Conjunto Laise Bordado",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Azul", "Rosa", "Amarelo", "Verde"],
    img: "assets/prod-conjunto-laise-azul-1.jpg",
    images: [
      "assets/prod-conjunto-laise-azul-1.jpg",
      "assets/prod-conjunto-laise-azul-2.jpg",
      "assets/prod-conjunto-laise-azul-3.jpg",
      "assets/prod-conjunto-laise-azul-4.jpg",
      "assets/prod-conjunto-laise-azul-5.jpg",
      "assets/prod-laise-cores.jpg",
    ],
    isNew: true,
    desc: "Top frente única em laise bordado + saia de babados em camadas. Última foto: as cores do tecido.",
  },
  {
    id: "vestido-babados-amarelo",
    name: "Vestido Babados Frente Única",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Amarelo"],
    img: "assets/prod-vestido-babados-amarelo.jpg",
    video: "assets/video-duo-amarelo.mp4",
    poster: "assets/video-duo-amarelo-poster.jpg",
    isNew: true,
    desc: "Vestido curto frente única com franzido no busto e saia de babados em camadas. No vídeo, junto com o vestido de renda um ombro só.",
  },
  {
    id: "vestido-marrom-ombro",
    name: "Vestido Ombro a Ombro Franzido",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Marrom"],
    img: "assets/prod-vestido-marrom.jpg",
    video: "assets/video-vestido-marrom.mp4",
    poster: "assets/video-vestido-marrom-poster.jpg",
    isNew: true,
    desc: "Vestido curto ombro a ombro de manga longa, todo franzido no corpo. Veja o caimento no vídeo.",
  },
  {
    id: "conjunto-paete",
    name: "Conjunto Paetê Top + Short",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Preto"],
    img: "assets/prod-conjunto-paete.jpg",
    video: "assets/video-conjunto-paete.mp4",
    poster: "assets/video-conjunto-paete-poster.jpg",
    isNew: true,
    desc: "Top de alcinha e short em paetê preto. Brilho na medida pra festa. Veja o caimento no vídeo.",
  },
  {
    id: "vestido-laise-camadas",
    name: "Vestido Laise Camadas",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Bege"],
    img: "assets/prod-vestido-laise.jpg",
    video: "assets/video-vestido-laise.mp4",
    poster: "assets/video-vestido-laise-poster.jpg",
    isNew: true,
    desc: "Vestido curto em laise com amarração no pescoço, laço no busto e saia de babados em camadas. Veja o caimento no vídeo.",
  },
  {
    id: "vestido-paete-tomara",
    name: "Vestido Paetê Tomara que Caia",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Preto"],
    img: "assets/prod-vestido-paete.jpg",
    video: "assets/video-vestido-paete.mp4",
    poster: "assets/video-vestido-paete-poster.jpg",
    isNew: true,
    desc: "Vestido tomara que caia em paetê preto, com drapeado lateral assimétrico. Veja o caimento no vídeo.",
  },
  {
    id: "top-renda-amarelo",
    name: "Top Renda Alcinha",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Amarelo"],
    img: "assets/prod-top-renda-amarelo.jpg",
    isNew: true,
    desc: "Top de alcinha em renda, forrado, com acabamento delicado. Peça queridinha das clientes teen.",
  },
  {
    id: "conjunto-preto",
    name: "Conjunto Blusa Ombro + Saia",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Preto"],
    img: "assets/prod-conjunto-preto.jpg",
    isNew: false,
    desc: "Conjunto blusa manga curta assimétrica + minissaia. Caimento justo, tecido premium com elastano.",
  },
  {
    id: "regata-alcinha-babado",
    name: "Regata Alcinha Babado",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Azul", "Rosa", "Preto"],
    img: "assets/prod-camisole-3cores.jpg",
    isNew: true,
    bestSeller: true,
    desc: "Regata de alcinha com babado no busto, tecido leve. Disponível em 3 cores — o item mais pedido pelas lojistas.",
  },
  {
    id: "top-frente-unica-laise",
    name: "Top Frente Única Laise",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Amarelo", "Branco", "Preto"],
    img: "assets/prod-halter-3cores.jpg",
    isNew: true,
    bestSeller: true,
    desc: "Top frente única em laise bordado, com três camadas de babado e alça trançada de amarrar no pescoço. Sai em 3 cores.",
  },
  {
    id: "conjunto-cropped-saia-duo",
    name: "Conjunto Cropped + Saia Amarrada",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Azul", "Rosa"],
    img: "assets/prod-conjunto-duo-video.jpg",
    images: [
      "assets/prod-conjunto-duo-video.jpg",
      "assets/prod-conjunto-rosa-1.jpg",
      "assets/prod-conjunto-rosa-2.jpg",
      "assets/prod-conjunto-rosa-3.jpg",
    ],
    video: "assets/hero-conjunto-duo.mp4",
    poster: "assets/hero-conjunto-duo-poster.jpg",
    isNew: false,
    desc: "Cropped ombro a ombro + saia curta com faixa amarrada lateral. Tecido canelado com caimento.",
  },
  {
    id: "top-alcinha-azul",
    name: "Top Assimétrico Franzido",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Azul"],
    img: "assets/prod-top-azul-video.jpg",
    video: "assets/video-top-azul.mp4",
    poster: "assets/video-top-azul-poster.jpg",
    isNew: false,
    desc: "Top assimétrico com franzido lateral e alça de amarrar no ombro. Veja o caimento no vídeo.",
  },
  {
    id: "conjunto-renda-branco",
    name: "Conjunto Corselet Renda Branco",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Branco"],
    img: "assets/prod-conjunto-renda-branco.jpg",
    video: "assets/video-corselet-branco.mp4",
    poster: "assets/video-corselet-branco-poster.jpg",
    isNew: false,
    desc: "Corselet em renda floral com amarração + shorts liso. Visual romântico, best-seller de verão.",
  },
  {
    id: "vestido-tubinho-rosa",
    name: "Vestido Tubinho Renda",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Rosa"],
    img: "assets/prod-vestido-rosa.jpg",
    isNew: false,
    desc: "Vestido tubinho tomara-que-caia em renda texturizada, forrado, comprimento curto.",
  },
  {
    id: "vestido-babados-azul",
    name: "Vestido Ombro a Ombro Babados",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Azul"],
    img: "assets/prod-vestido-azul.jpg",
    isNew: false,
    desc: "Vestido ombro a ombro com saia de babados sobrepostos e cinto. Ideal pra festa/evento.",
  },
  {
    id: "vestido-renda-amarelo-unico",
    name: "Vestido Renda Um Ombro Só",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Amarelo"],
    img: "assets/prod-vestido-amarelo-unico.jpg",
    video: "assets/video-duo-amarelo.mp4",
    poster: "assets/video-duo-amarelo-poster.jpg",
    isNew: true,
    bestSeller: true,
    desc: "Vestido em renda floral all-over, um ombro só. Um dos mais vendidos da coleção.",
  },
  {
    id: "vestido-azul-renda-cutout",
    name: "Vestido Azul Recorte Lateral",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Azul"],
    img: "assets/prod-vestido-azul-renda-1.jpg",
    images: [
      "assets/prod-vestido-azul-renda-1.jpg",
      "assets/prod-vestido-azul-renda-2.jpg",
      "assets/prod-vestido-azul-renda-3.jpg",
    ],
    isNew: true,
    bestSeller: true,
    desc: "Vestido curto em renda azul bebê, recorte lateral na cintura e barra com camadas de babado. Fotos de frente e de costas.",
  },
  {
    id: "vestido-drapeado-azul",
    name: "Vestido Um Ombro Drapeado",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Azul"],
    img: "assets/prod-vestido-drapeado-azul.jpg",
    video: "assets/hero-vestido-azul.mp4",
    poster: "assets/hero-vestido-azul-poster.jpg",
    isNew: true,
    desc: "Vestido curto de um ombro só, franzido no corpo e faixa amarrada na lateral. Veja o caimento no vídeo.",
  },
  {
    id: "vestido-amarelo-camadas",
    name: "Vestido Camadas Amarelo",
    category: "vestidos",
    categoryLabel: "Vestidos",
    colors: ["Amarelo"],
    img: "assets/prod-vestido-amarelo-camadas-1.jpg",
    images: [
      "assets/prod-vestido-amarelo-camadas-1.jpg",
      "assets/prod-vestido-amarelo-camadas-2.jpg",
      "assets/prod-vestido-amarelo-camadas-3.jpg",
    ],
    isNew: true,
    desc: "Vestido longo com recorte na cintura e saia de camadas sobrepostas. Fotos de frente e de costas.",
  },
  {
    id: "top-floral-lilas",
    name: "Top Alça Floral",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Lilás"],
    img: "assets/prod-top-floral-lilas.jpg",
    isNew: true,
    desc: "Top de alcinha estampa floral lilás, tecido leve e fluido. Combina com shorts ou saia.",
  },
  {
    id: "conjunto-croche-amarelo",
    name: "Conjunto Top Crochê + Saia",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Amarelo"],
    img: "assets/prod-conjunto-croche-amarelo.jpg",
    isNew: true,
    desc: "Top halter em crochê com camadas + minissaia preta. Textura artesanal, visual romântico.",
  },
  {
    id: "top-renda-rosa",
    name: "Top Ombro Renda Rosa",
    category: "tops",
    categoryLabel: "Tops",
    colors: ["Rosa"],
    img: "assets/prod-top-renda-rosa.jpg",
    isNew: false,
    desc: "Top com babado nos ombros em tecido texturizado rosa. Peça coringa pro dia a dia.",
  },
  {
    id: "conjunto-renda-rosa",
    name: "Conjunto Top Renda + Saia Rosa",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    colors: ["Rosa"],
    img: "assets/prod-conjunto-renda-rosa.jpg",
    isNew: false,
    desc: "Top de renda transparente com forro + minissaia rosa. Visual delicado e sofisticado.",
  },
];

// Torna acessível tanto em <script> normal quanto se algum dia virar módulo.
if (typeof window !== "undefined") window.PRODUCTS = PRODUCTS;
